from typing import List, TypedDict



class GraphState(TypedDict):
    """Represents the state of the graph"""

    """Attributes:
    question: The question the user will ask(string)
    generation: The response generated by the LLM
    web_search: A boolean value representing if web search is needed for that user question
    documents: The related documents fetched from the vector store
    """

    question: str
    generation: str
    web_search: bool
    documents: List[str]